#!/bin/bash
FROM node:latest
WORKDIR /usr/src/app/simplegmail_frontend

COPY client/package*.json ./

RUN npm install --production

COPY client .
EXPOSE 4000
CMD ["npm", "run", "serve", "--", "--port", "4000"]
