#!/bin/bash
FROM node:latest
# Create app directory
WORKDIR /usr/src/app/simplegmail_backend
# Install app dependencies
COPY server/package*.json ./
RUN npm install
RUN npm install pm2 -g
# Copy app source code
COPY server .
#Expose port and start application
EXPOSE 6080
CMD [ "pm2-runtime", "server.js" ]
