#!/bin/bash
FROM node:12
WORKDIR /usr/src/app/simplegmail_frontend

COPY client/package*.json ./

RUN npm install
RUN npm update --force
COPY client .
EXPOSE 4000
CMD ["npm", "run", "serve", "--", "--port", "4000"]
