#!/bin/bash
FROM node:latest
RUN npm install -g http-server
WORKDIR /usr/src/app/simplegmail_frontend

COPY client/package*.json ./

RUN npm install

COPY client .
RUN npm run build
EXPOSE 4000
CMD [ "http-server", "dist", "-p", "4000", "-P", "http://localhost:4000?"  ]
