version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    ports:
      - "4000:4000"
    container_name: simplegmail_frontend
    environment:
      - TARGET_URL=http://backend:4080
      - PORT=4000
      - VUE_APP_ENV=development
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile_Backend
    ports:
      - "4080:4080"
    container_name: simplegmail_backend
    environment:
      - port=4080
      - HOST=mongo-db-simplegmail
      - GOOGLE_CREDENTIALS={"web":{"client_id":"417728105098-urn8v0e481l1mthrs3i3ltn1jumpejsk.apps.googleusercontent.com","project_id":"simplegmail-324011","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"1gDNBfX9MxdUN_pK0DcSTqwO","redirect_uris":["http://localhost:3000/googlecallback"]}}
      - MONGODB_PORT=27017
      - NODE_APP_ENV=development
      - JWT_SECRET=simplegmail
      - DB_NAME=simplegmail
      - FRONT_URL=https://simplegmail.plenartech.com/
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - database
  database:
    image: mongo
    environment:
      - DOCKER=1
    container_name: mongo-db-simplegmail
    volumes:
      - mongodb:/data/db
    ports:
      - "27018:27017"
    restart: always
volumes:
  mongodb: